export const resumeKeywords = [
  // --- Personal Identity (Authorized User) ---
  "Sushant Kushwaha",
  "Sushant Kushwaha resume",
  "Sushant Kushwaha CV",
  "Sushant Kushwaha Portfolio",
  "Software Developer",
  "Full Stack Developer",
  "Web Developer",
  "Frontend Engineer",
  "Junior Developer",
  "Student Developer",
  "Next.js Developer",
  "TypeScript Enthusiast",
  "Class 12 Computer Science",
  "Nepal Developer",

  // --- Programming Languages (Syntax) ---
  "JavaScript",
  "TypeScript",
  "Python",
  "C++",
  "C Programming",
  "HTML5",
  "CSS3",
  "SQL",
  "NoSQL",

  // --- Modern Frontend (UI/UX Architecture) ---
  "React.js",
  "Next.js",
  "Tailwind CSS",
  "Framer Motion",
  "ShadCN UI",
  "Radix UI",
  "Responsive Web Design",
  "Mobile-First Development",
  "Glassmorphism",
  "Dark Mode Optimization",
  "Server Components",
  "Client-Side Rendering",

  // --- Backend & E-commerce (Logic Core) ---
  "Node.js",
  "Express.js",
  "MedusaJS",
  "E-commerce Development",
  "RESTful APIs",
  "API Integration",
  "Authentication",
  "JWT",
  "Middleware",
  "Stripe Integration",
  "Serverless Functions",

  // --- Database & Storage (Data persistence) ---
  "PostgreSQL",
  "MongoDB",
  "Firebase",
  "Supabase",
  "Prisma ORM",
  "Drizzle ORM",
  "Redis",
  "Data Modeling",

  // --- DevOps & Infrastructure (Uplink) ---
  "Git",
  "GitHub",
  "Version Control",
  "Vercel Deployment",
  "Netlify",
  "Docker",
  "CI/CD Pipelines",
  "npm",
  "pnpm",
  "Vite",
  "Postman API Testing",

  // --- Hardware & DIY (Cyber-Physical) ---
  "ESP32",
  "Arduino",
  "IoT Development",
  "Embedded Systems",
  "Hardware Troubleshooting",
  "Network Security",
  "WiFi Deauther Project",
  "Microcontrollers",
  "Circuit Design",

  // --- AI & Neural Systems ---
  "Generative AI",
  "OpenAI API",
  "ChatGPT Integration",
  "Prompt Engineering",
  "LLM Applications",
  "Large Language Models",

  // --- Architecture & Principles ---
  "Object-Oriented Programming",
  "OOP",
  "Functional Programming",
  "Clean Code",
  "SOLID Principles",
  "MVC Architecture",
  "System Design",
  "Performance Optimization",
  "Code Refactoring",

  // --- Logic & Problem Solving ---
  "Data Structures",
  "Algorithms",
  "Big O Notation",
  "Problem Solving",
  "Searching Algorithms",
  "Sorting Algorithms",
  "Recursion",

  // --- Soft Skills & Professional ---
  "Critical Thinking",
  "Self-Motivated",
  "Adaptive Learning",
  "Detail Oriented",
  "Technical Documentation",
  "Continuous Learning",
  "Creative Problem Solving",

  // --- Location & Availability (Status: Ready) ---
  "Kathmandu, Nepal",
  "Nepal",
  "Remote Work",
  "Available for Internship",
  "Freelance Available",
  "Hybrid Work",
  "Available Immediately",
];